### ISSUE TITLE
 Regarding the runtime error

### ISSUE THREAD

**Issue by applelalala** [prassepaul/mlmed_ranking#2]
After running the code, the following error occurred:    
Traceback (most recent call last):
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\eager\context.py", line 843, in _mode
    yield
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 350, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1176, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1209, in _train_model_default
    saving_listeners)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1515, in _train_with_estimator_spec
    save_graph_def=self._config.checkpoint_save_graph_def) as mon_sess:
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\monitored_session.py", line 605, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1039, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\monitored_session.py", line 750, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1232, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1237, in _create_session
    return self._sess_creator.create_session()
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\monitored_session.py", line 910, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 587, in after_create_session
    self._save(session, global_step)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 620, in _save
    write_meta_graph=self._save_graph_def)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\training\saver.py", line 1190, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "D:\Users\admin\anaconda3\envs\refdnn\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 192: invalid continuation byte                          

I suspect there might be an issue with the TFRecord file, but the data is provided within the code. I'm not sure how to resolve this problem. Can you help me?

**Comment by prassepaul** [comment]
This looks like an internal error of your installed environment. I added a *.yml file, from which you can create an environment that should be able to run the code. The TFRecord files are created on the fly using the CSV-files with the data.
